"""
drive_service.py — Google Drive API helpers.

Auth strategy (auto-detected):
  Local:      loads credentials.json + token.json from disk
  Cloud:      loads from st.secrets["GOOGLE_CREDENTIALS"] / ["GOOGLE_TOKEN"]
              (Streamlit Community Cloud deployment)
"""

from __future__ import annotations
import io
import json
import logging
import os
import tempfile
from functools import lru_cache

from googleapiclient.discovery import build, Resource
from googleapiclient.http import MediaIoBaseUpload

from config import CREDENTIALS_PATH, GOOGLE_SCOPES as SCOPES

logger = logging.getLogger(__name__)
TOKEN_PATH = "token.json"
import threading
_FOLDER_LOCK = threading.Lock() # Prevent duplicate folder creation in parallel runs


def _is_streamlit_cloud() -> bool:
    """Detect Streamlit Cloud environment by checking st.secrets."""
    try:
        import streamlit as st
        return (
            hasattr(st, "secrets")
            and "GOOGLE_CREDENTIALS" in st.secrets
        )
    except Exception:
        return False


@lru_cache(maxsize=1)
def _load_credentials():
    """Auto-detect environment and return authenticated Google credentials."""

    # ── Streamlit Cloud: load from st.secrets ──────────────────────────────────
    if _is_streamlit_cloud():
        import streamlit as st
        from google.oauth2.credentials import Credentials
        from google.auth.transport.requests import Request

        token_info = json.loads(st.secrets["GOOGLE_TOKEN"])
        creds = Credentials.from_authorized_user_info(token_info, SCOPES)

        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            logger.info("Auth: OAuth2 token refreshed (cloud mode).")

        logger.info("Auth: Loaded from st.secrets (cloud mode).")
        return creds

    # ── Local: auto-detect from credentials.json file type ────────────────────
    with open(CREDENTIALS_PATH) as f:
        data = json.load(f)

    # Service Account
    if data.get("type") == "service_account":
        from google.oauth2 import service_account
        logger.info("Auth: Service Account (%s)", data.get("client_email", ""))
        return service_account.Credentials.from_service_account_file(
            CREDENTIALS_PATH, scopes=SCOPES
        )

    # OAuth2 — require token.json (generated by setup_auth.py)
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request

    if not os.path.exists(TOKEN_PATH):
        raise RuntimeError(
            "נדרש אישור OAuth2. הרץ פעם אחת בטרמינל:\n\n"
            "    uv run python setup_auth.py\n\n"
            "אחרי האישור, הפעל מחדש את האפליקציה."
        )

    creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)

    if creds and creds.valid:
        logger.debug("Auth: OAuth2 token loaded from %s", TOKEN_PATH)
        return creds

    if creds and creds.expired and creds.refresh_token:
        try:
            creds.refresh(Request())
            with open(TOKEN_PATH, "w") as t:
                t.write(creds.to_json())
            logger.info("Auth: OAuth2 token refreshed.")
            return creds
        except Exception as exc:
            logger.warning("Token refresh failed: %s", exc)

    raise RuntimeError(
        "טוקן OAuth2 לא תקין. הרץ: uv run python setup_auth.py"
    )


def get_drive_service() -> Resource:
    """Build and return an authenticated Google Drive service."""
    import httplib2
    import google_auth_httplib2
    creds = _load_credentials()
    
    # To fix SSL record layer issues in multi-threading, we must use an isolated HTTP object.
    # However, 'http' and 'credentials' are mutually exclusive in build().
    # We must wrap the isolated http object with credentials using AuthorizedHttp.
    http = httplib2.Http()
    authed_http = google_auth_httplib2.AuthorizedHttp(creds, http=http)
    
    service = build("drive", "v3", http=authed_http, cache_discovery=False)
    logger.debug("Google Drive service initialised with isolated authorized transport.")
    return service


def find_folder(service: Resource, name: str, parent_id: str) -> str | None:
    """Return folder ID if a folder with the given name exists under parent_id."""
    query = (
        f"name='{name}' "
        f"and mimeType='application/vnd.google-apps.folder' "
        f"and '{parent_id}' in parents "
        f"and trashed=false"
    )
    result = (
        service.files()
        .list(
            q=query,
            fields="files(id, name)",
            supportsAllDrives=True,
            includeItemsFromAllDrives=True,
        )
        .execute()
    )
    files = result.get("files", [])
    return files[0]["id"] if files else None


def create_folder(service: Resource, name: str, parent_id: str) -> str:
    """Create a folder under parent_id and return its new ID."""
    file_metadata = {
        "name": name,
        "mimeType": "application/vnd.google-apps.folder",
        "parents": [parent_id],
    }
    folder = (
        service.files()
        .create(body=file_metadata, fields="id", supportsAllDrives=True)
        .execute()
    )
    folder_id = folder["id"]
    logger.debug("Created folder '%s' (id=%s)", name, folder_id)
    return folder_id


def find_or_create_folder(service: Resource, name: str, parent_id: str) -> str:
    """Find or create a folder by name under parent_id. Returns folder ID."""
    with _FOLDER_LOCK:
        existing = find_folder(service, name, parent_id)
        if existing:
            logger.debug("Found existing folder '%s' (id=%s)", name, existing)
            return existing
        return create_folder(service, name, parent_id)


def upload_file(
    service: Resource,
    file_bytes: bytes,
    filename: str,
    mime_type: str,
    parent_id: str,
) -> tuple[str, str]:
    """Upload a file to Google Drive. Returns (file_id, web_view_link)."""
    media = MediaIoBaseUpload(io.BytesIO(file_bytes), mimetype=mime_type, resumable=True)
    file_metadata = {"name": filename, "parents": [parent_id]}
    uploaded = (
        service.files()
        .create(
            body=file_metadata,
            media_body=media,
            fields="id, webViewLink",
            supportsAllDrives=True,
        )
        .execute()
    )
    file_id = uploaded["id"]
    link = uploaded.get("webViewLink", f"https://drive.google.com/file/d/{file_id}/view")
    logger.debug("Uploaded '%s' → %s", filename, link)
    return file_id, link
